apiVersion: v1
kind: Service
metadata:
  name: solrcluster
  labels:
    app: solr-app-cluster
spec:
  clusterIP: None
  selector:
    app: solr-app
---
apiVersion: v1
kind: Service
metadata:
  name: solr-service
  labels:
    app: solr-app
spec:
  ports:
  - protocol: TCP
    port: 8983
    targetPort: 8983
  type: ClusterIP
  selector:
    app: solr-app
