kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: store-solrcluster
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Delete
allowVolumeExpansion: true
parameters:
  skuName: Premium_LRS
  kind: Managed
  storageaccounttype: Premium_LRS
#  fsType: xfs
#  location: eastus
